package io.committed.krill.extraction.tika.pdf;

import io.committed.krill.extraction.tika.helper.AbstractTikaFormatExtractorIT;
import org.junit.Test;

public class PdfTableFormatExtractorIT extends AbstractTikaFormatExtractorIT {

  public PdfTableFormatExtractorIT() {
    super("tables.pdf");
  }

  @Test
  public void testBody() {
    assertBody("" + "<main class=\"Document\"> \n" + " <article class=\"page\"> \n" + "  <table> \n"
        + "   <tbody> \n" + "    <tr></tr> \n" + "   </tbody> \n" + "  </table> \n"
        + "  <p style=\"font-family:Calibri-Light;font-size:12.0pt;color:#1f4d78\">Tables</p> \n"
        + "  <p style=\"font-family:Calibri;font-size:12.0\">Here is a simple text table:</p> \n"
        + "  <table> \n" + "   <tbody> \n" + "    <tr></tr> \n" + "    <tr> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">1a</p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">1b</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">1c</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">1d</p> </td> \n"
        + "    </tr> \n" + "    <tr> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">2a</p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">2b</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">2c</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">2d</p> </td> \n"
        + "    </tr> \n" + "    <tr> \n" + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n" + "    </tr> \n" + "    <tr> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">3a</p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">3b</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">3c</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">3d</p> </td> \n"
        + "    </tr> \n" + "   </tbody> \n" + "  </table> \n"
        + "  <p style=\"font-family:Calibri;font-size:12.0\">They can have title rows and styles applied (in this case ‘Plain Table 3’):</p> \n"
        + "  <table> \n" + "   <tbody> \n" + "    <tr></tr> \n" + "    <tr> \n"
        + "     <td style=\"font-family:Calibri-Bold;font-size:12.0\" colspan=\"3\" rowspan=\"1\"><p style=\"font-family:Calibri-Bold;font-size:12.0\"><b>A</b></p> </td> \n"
        + "     <td style=\"font-family:Calibri-Bold;font-size:12.0\" colspan=\"3\" rowspan=\"1\"><p style=\"font-family:Calibri-Bold;font-size:12.0\"><b>B</b></p> </td> \n"
        + "     <td style=\"font-family:Calibri-Bold;font-size:12.0\" colspan=\"3\" rowspan=\"1\"><p style=\"font-family:Calibri-Bold;font-size:12.0\"><b>C</b></p> </td> \n"
        + "     <td style=\"font-family:Calibri-Bold;font-size:12.0\" colspan=\"3\" rowspan=\"1\"><p style=\"font-family:Calibri-Bold;font-size:12.0\"><b>D</b></p> </td> \n"
        + "    </tr> \n" + "    <tr> \n" + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">1d</p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n" + "    </tr> \n" + "    <tr> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">2d</p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n" + "    </tr> \n" + "    <tr> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">3d</p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n" + "    </tr> \n"
        + "   </tbody> \n" + "  </table> \n" + "  <table> \n" + "   <tbody> \n" + "    <tr> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\"><p style=\"font-family:Calibri;font-size:12.0\">1a</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\"><p style=\"font-family:Calibri;font-size:12.0\">1b</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\"><p style=\"font-family:Calibri;font-size:12.0\">1c</p> </td> \n"
        + "    </tr> \n" + "    <tr> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\"><p style=\"font-family:Calibri;font-size:12.0\">2a</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\"><p style=\"font-family:Calibri;font-size:12.0\">2b</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\"><p style=\"font-family:Calibri;font-size:12.0\">2c</p> </td> \n"
        + "    </tr> \n" + "    <tr> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\"><p style=\"font-family:Calibri;font-size:12.0\">3a</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\"><p style=\"font-family:Calibri;font-size:12.0\">3b</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\"><p style=\"font-family:Calibri;font-size:12.0\">3c</p> </td> \n"
        + "    </tr> \n" + "   </tbody> \n" + "  </table> \n"
        + "  <p style=\"font-family:Calibri;font-size:12.0\">Tables can contain almost any element, as with HTML,</p> \n"
        + "  <ul style=\"font-family:SymbolMT;font-size:12.0\" colspan=\"1\" rowspan=\"4\"> \n"
        + "   <li></li> \n" + "   <li> One </li> \n" + "   <li> Two </li> \n"
        + "   <li> Three</li> \n" + "  </ul>\n"
        + "  <ul style=\"font-family:SymbolMT;font-size:12.0\" colspan=\"1\" rowspan=\"1\"> \n"
        + "   <li></li> \n" + "   <li> Alpha </li> \n" + "   <li> Beta</li> \n" + "  </ul>\n"
        + "  <table> \n" + "   <tbody> \n" + "    <tr></tr> \n" + "    <tr>  \n"
        + "     <td colspan=\"1\" rowspan=\"4\"><p></p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">Including</p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">Nested</p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">Tables</p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"4\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">Oh</p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n" + "    </tr> \n" + "    <tr>  \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n"
        + "     <td style=\"font-family:Calibri;font-size:12.0\" colspan=\"6\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:12.0\">And images, SmartArt,<br> etc. Here is a Shape (a<br> Cloud) containing some<br> text – because every<br> technical document<br> should mention clouds.</p> </td> \n"
        + "     <td colspan=\"1\" rowspan=\"1\"><p></p> </td> \n" + "    </tr> \n"
        + "   </tbody> \n" + "  </table> \n"
        + "  <p style=\"font-family:Calibri;font-size:12.0\">Why</p> \n"
        + "  <p style=\"font-family:Calibri;font-size:12.0\">Why</p> \n" + "  <table> \n"
        + "   <tbody> \n" + "    <tr></tr> \n" + "    <tr> \n"
        + "     <td style=\"font-family:Calibri;font-size:8.0pt;color:#ffffff\" colspan=\"1\" rowspan=\"1\"><p style=\"font-family:Calibri;font-size:8.0pt;color:#ffffff\">It is just someone<br> elses computer!</p> </td> \n"
        + "    </tr> \n" + "   </tbody> \n" + "  </table> \n" + " </article> \n" + "</main>");
  }

}
